name: Update CONTRIBUTORS file
on:
  push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: padmashree12/github-workflow-try@dfghgfhghgh
        with:
          repo: ${{ github.repository }}
        name: 'Update a projects CONTRIBUTORS file'
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: Update Contributors
          github-token: ${{ secrets.GITHUB_TOKEN }}
